defaults:
  # important configs defining data and model
  - data: datamodule
  - model: segmentor
  # configs defining logging and callbacks
  - callbacks: default
  - logger: wandb
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default
  - _self_

modelname: drifts

model:
  net:
    out_channels: 8
  num_classes: 8

data:
  split_file: /media/vzalevskyi/data/FETA_challenge/deletme/participants_testvlad.csv
  bids_path: /media/vzalevskyi/data/FETA_challenge/deletme/
  seed_path: null

  num_workers: 12
  batch_size: 1
  img_suffix: T2w
  seg_suffix: a
  load_segmentations: false

  transforms:
    _target_: monai.transforms.Compose
    transforms:
      - _target_: monai.transforms.Orientationd
        keys: ["image", "label"]
        axcodes: "RAS"
        allow_missing_keys: true

      - _target_: monai.transforms.SignalFillEmptyd
        keys: ["image", "label"]
        replacement: 0
        allow_missing_keys: true

      - _target_: monai.transforms.Spacingd
        keys: ["image", "label"]
        pixdim: [0.5, 0.5, 0.5]
        mode: ["bilinear", "nearest"]
        allow_missing_keys: true

      - _target_: monai.transforms.SpatialPadd
        keys: ["image", "label"]
        spatial_size: [256, 256, 256]
        mode: "constant"
        allow_missing_keys: true

      - _target_: monai.transforms.CenterSpatialCropd
        keys: ["image", "label"]
        roi_size: [256, 256, 256]
        allow_missing_keys: true

      - _target_: monai.transforms.ScaleIntensityd
        keys: ["image"]
        minv: 0
        maxv: 1


save_path: /media/vzalevskyi/data/FETA_challenge/deletme/derivatives/inference

test_splits:
  - test


device: cuda:0
# passing checkpoint paths is necessary for evaluation
ckpt_paths:
  - /mnt/Home2/projects/segsynthtemplate/None/logs/fetaall_synth_ftreal_interp05/runs/2025-05-20_18-44-49/checkpoints/interp.ckpt

hydra:
  run:
    dir: .
  output_subdir: null

task_name: "eval"

tags: ["dev"]
